version: '3'
services:
  mongo:
    image: mongo:3
    container_name: schedule_mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - net_schedule
networks:
  net_schedule:
    driver: bridge